// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// spListPerCell
List spListPerCell(NumericMatrix input);
RcppExport SEXP speciesRaster_spListPerCell(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(spListPerCell(input));
    return rcpp_result_gen;
END_RCPP
}
// sort_
NumericVector sort_(NumericVector x, int cutoff);
RcppExport SEXP speciesRaster_sort_(SEXP xSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(sort_(x, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// returnTopIndices
List returnTopIndices(NumericMatrix input, IntegerVector cutoff);
RcppExport SEXP speciesRaster_returnTopIndices(SEXP inputSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(returnTopIndices(input, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// cellAvg
NumericVector cellAvg(List input, NumericVector trait, String stat);
RcppExport SEXP speciesRaster_cellAvg(SEXP inputSEXP, SEXP traitSEXP, SEXP statSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trait(traitSEXP);
    Rcpp::traits::input_parameter< String >::type stat(statSEXP);
    rcpp_result_gen = Rcpp::wrap(cellAvg(input, trait, stat));
    return rcpp_result_gen;
END_RCPP
}
// intersectList
List intersectList(List input, StringVector vec);
RcppExport SEXP speciesRaster_intersectList(SEXP inputSEXP, SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< List >::type input(inputSEXP);
    Rcpp::traits::input_parameter< StringVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(intersectList(input, vec));
    return rcpp_result_gen;
END_RCPP
}
