# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spListPerCell <- function(input) {
    .Call('_speciesRaster_spListPerCell', PACKAGE = 'speciesRaster', input)
}

sort_ <- function(x, cutoff) {
    .Call('_speciesRaster_sort_', PACKAGE = 'speciesRaster', x, cutoff)
}

returnTopIndices <- function(input, cutoff) {
    .Call('_speciesRaster_returnTopIndices', PACKAGE = 'speciesRaster', input, cutoff)
}

meanNNdist <- function(input) {
    .Call('_speciesRaster_meanNNdist', PACKAGE = 'speciesRaster', input)
}

minNNdist <- function(input) {
    .Call('_speciesRaster_minNNdist', PACKAGE = 'speciesRaster', input)
}

cellAvg <- function(input, trait, stat) {
    .Call('_speciesRaster_cellAvg', PACKAGE = 'speciesRaster', input, trait, stat)
}

intersectList <- function(input, vec) {
    .Call('_speciesRaster_intersectList', PACKAGE = 'speciesRaster', input, vec)
}

flattenMatrix <- function(mat) {
    .Call('_speciesRaster_flattenMatrix', PACKAGE = 'speciesRaster', mat)
}

LegendreDiffIndex <- function(commA, commB) {
    .Call('_speciesRaster_LegendreDiffIndex', PACKAGE = 'speciesRaster', commA, commB)
}

jaccardDissimilarity <- function(commA, commB) {
    .Call('_speciesRaster_jaccardDissimilarity', PACKAGE = 'speciesRaster', commA, commB)
}

jaccardTurnover <- function(commA, commB) {
    .Call('_speciesRaster_jaccardTurnover', PACKAGE = 'speciesRaster', commA, commB)
}

jaccardNestedness <- function(commA, commB) {
    .Call('_speciesRaster_jaccardNestedness', PACKAGE = 'speciesRaster', commA, commB)
}

ListIsEmpty <- function(input) {
    .Call('_speciesRaster_ListIsEmpty', PACKAGE = 'speciesRaster', input)
}

ListIsEmptyR <- function(input) {
    .Call('_speciesRaster_ListIsEmptyR', PACKAGE = 'speciesRaster', input)
}

whichCpp <- function(x) {
    .Call('_speciesRaster_whichCpp', PACKAGE = 'speciesRaster', x)
}

characterUnlist <- function(list) {
    .Call('_speciesRaster_characterUnlist', PACKAGE = 'speciesRaster', list)
}

naomit <- function(x) {
    .Call('_speciesRaster_naomit', PACKAGE = 'speciesRaster', x)
}

dropNeg <- function(x) {
    .Call('_speciesRaster_dropNeg', PACKAGE = 'speciesRaster', x)
}

multiPrepCpp <- function(allComm) {
    .Call('_speciesRaster_multiPrepCpp', PACKAGE = 'speciesRaster', allComm)
}

multiPrep <- function(allComm) {
    .Call('_speciesRaster_multiPrep', PACKAGE = 'speciesRaster', allComm)
}

betaJAC <- function(vec) {
    .Call('_speciesRaster_betaJAC', PACKAGE = 'speciesRaster', vec)
}

betaJTU <- function(vec) {
    .Call('_speciesRaster_betaJTU', PACKAGE = 'speciesRaster', vec)
}

betaJNE <- function(vec) {
    .Call('_speciesRaster_betaJNE', PACKAGE = 'speciesRaster', vec)
}

betaSOR <- function(vec) {
    .Call('_speciesRaster_betaSOR', PACKAGE = 'speciesRaster', vec)
}

betaSIM <- function(vec) {
    .Call('_speciesRaster_betaSIM', PACKAGE = 'speciesRaster', vec)
}

betaSNE <- function(vec) {
    .Call('_speciesRaster_betaSNE', PACKAGE = 'speciesRaster', vec)
}

calcBetaPairwise <- function(spByCell, nbList, metric) {
    .Call('_speciesRaster_calcBetaPairwise', PACKAGE = 'speciesRaster', spByCell, nbList, metric)
}

calcBetaMultiSite <- function(spByCell, nbList, metric) {
    .Call('_speciesRaster_calcBetaMultiSite', PACKAGE = 'speciesRaster', spByCell, nbList, metric)
}

calcBetaMultiSiteBlock <- function(spByCell, nbList, metric) {
    .Call('_speciesRaster_calcBetaMultiSiteBlock', PACKAGE = 'speciesRaster', spByCell, nbList, metric)
}

mapComm <- function(uniqueCommLabels, allComm) {
    .Call('_speciesRaster_mapComm', PACKAGE = 'speciesRaster', uniqueCommLabels, allComm)
}

c_which_int <- function(vec, x) {
    .Call('_speciesRaster_c_which_int', PACKAGE = 'speciesRaster', vec, x)
}

getRootToTipEdges <- function(phylo) {
    .Call('_speciesRaster_getRootToTipEdges', PACKAGE = 'speciesRaster', phylo)
}

phyloBranchRanges <- function(phylo, speciesList, tipEdges) {
    .Call('_speciesRaster_phyloBranchRanges', PACKAGE = 'speciesRaster', phylo, speciesList, tipEdges)
}

countCells <- function(cellList, vec) {
    .Call('_speciesRaster_countCells', PACKAGE = 'speciesRaster', cellList, vec)
}

mergeLists <- function(input) {
    .Call('_speciesRaster_mergeLists', PACKAGE = 'speciesRaster', input)
}

getComponentA <- function(commI, commJ) {
    .Call('_speciesRaster_getComponentA', PACKAGE = 'speciesRaster', commI, commJ)
}

getComponentB <- function(commI, commJ) {
    .Call('_speciesRaster_getComponentB', PACKAGE = 'speciesRaster', commI, commJ)
}

getComponentC <- function(commI, commJ) {
    .Call('_speciesRaster_getComponentC', PACKAGE = 'speciesRaster', commI, commJ)
}

c_which_char <- function(vec, x) {
    .Call('_speciesRaster_c_which_char', PACKAGE = 'speciesRaster', vec, x)
}

weightedPhylo <- function(a, tipLabels, spEdges, edgeArea1, edgeArea2) {
    .Call('_speciesRaster_weightedPhylo', PACKAGE = 'speciesRaster', a, tipLabels, spEdges, edgeArea1, edgeArea2)
}

calcRWTurnover_taxonomic_old <- function(spByCell, nbList) {
    .Call('_speciesRaster_calcRWTurnover_taxonomic_old', PACKAGE = 'speciesRaster', spByCell, nbList)
}

calcRWTurnover_rangeWeighted_old <- function(spByCell, nbList, cellCountsR) {
    .Call('_speciesRaster_calcRWTurnover_rangeWeighted_old', PACKAGE = 'speciesRaster', spByCell, nbList, cellCountsR)
}

calcRWTurnover_phyloRangeWeighted_old <- function(spByCell, nbList, phylo, spEdges, edgeArea) {
    .Call('_speciesRaster_calcRWTurnover_phyloRangeWeighted_old', PACKAGE = 'speciesRaster', spByCell, nbList, phylo, spEdges, edgeArea)
}

calcRWTurnover_taxonomic_singleCell <- function(focalCell, nbList) {
    .Call('_speciesRaster_calcRWTurnover_taxonomic_singleCell', PACKAGE = 'speciesRaster', focalCell, nbList)
}

calcRWTurnover_rangeWeighted_singleCell <- function(focalCell, nbList, cellCountsR) {
    .Call('_speciesRaster_calcRWTurnover_rangeWeighted_singleCell', PACKAGE = 'speciesRaster', focalCell, nbList, cellCountsR)
}

calcRWTurnover_phyloRangeWeighted_singleCell <- function(focalCell, nbList, phyloTipLabels, spEdges, edgeArea) {
    .Call('_speciesRaster_calcRWTurnover_phyloRangeWeighted_singleCell', PACKAGE = 'speciesRaster', focalCell, nbList, phyloTipLabels, spEdges, edgeArea)
}

getCellFromRowCol <- function(rowInd, colInd, nCol) {
    .Call('_speciesRaster_getCellFromRowCol', PACKAGE = 'speciesRaster', rowInd, colInd, nCol)
}

getMovingWindowCells <- function(nRow, nCol, focalCell, radius, rasterValues) {
    .Call('_speciesRaster_getMovingWindowCells', PACKAGE = 'speciesRaster', nRow, nCol, focalCell, radius, rasterValues)
}

calcRWTurnover_taxonomic <- function(spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, showProgress) {
    .Call('_speciesRaster_calcRWTurnover_taxonomic', PACKAGE = 'speciesRaster', spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, showProgress)
}

calcRWTurnover_rangeWeighted <- function(spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, cellCountsR, showProgress) {
    .Call('_speciesRaster_calcRWTurnover_rangeWeighted', PACKAGE = 'speciesRaster', spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, cellCountsR, showProgress)
}

calcRWTurnover_phyloRangeWeighted <- function(spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, phylo, spEdges, edgeArea, showProgress) {
    .Call('_speciesRaster_calcRWTurnover_phyloRangeWeighted', PACKAGE = 'speciesRaster', spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, phylo, spEdges, edgeArea, showProgress)
}

getUnion <- function(vec1, vec2) {
    .Call('_speciesRaster_getUnion', PACKAGE = 'speciesRaster', vec1, vec2)
}

getLeavesForNodes <- function(phylo) {
    .Call('_speciesRaster_getLeavesForNodes', PACKAGE = 'speciesRaster', phylo)
}

getMRCA_from_nodeLeaves <- function(nodeLeaves, taxa) {
    .Call('_speciesRaster_getMRCA_from_nodeLeaves', PACKAGE = 'speciesRaster', nodeLeaves, taxa)
}

FaithPD_branchIndices <- function(a, phylo, nodeLeaves, spEdges) {
    .Call('_speciesRaster_FaithPD_branchIndices', PACKAGE = 'speciesRaster', a, phylo, nodeLeaves, spEdges)
}

calcPhylosor <- function(spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, phylo, showProgress) {
    .Call('_speciesRaster_calcPhylosor', PACKAGE = 'speciesRaster', spByCell, radius, rasterNRow, rasterNCol, rasterValuesR, nonNAcellsR, phylo, showProgress)
}

calcPhylosor2 <- function(spByCell, phylo, showProgress) {
    .Call('_speciesRaster_calcPhylosor2', PACKAGE = 'speciesRaster', spByCell, phylo, showProgress)
}

