# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spListPerCell <- function(input) {
    .Call('speciesRaster_spListPerCell', PACKAGE = 'speciesRaster', input)
}

sort_ <- function(x, cutoff) {
    .Call('speciesRaster_sort_', PACKAGE = 'speciesRaster', x, cutoff)
}

returnTopIndices <- function(input, cutoff) {
    .Call('speciesRaster_returnTopIndices', PACKAGE = 'speciesRaster', input, cutoff)
}

cellAvg <- function(input, trait, stat) {
    .Call('speciesRaster_cellAvg', PACKAGE = 'speciesRaster', input, trait, stat)
}

intersectList <- function(input, vec) {
    .Call('speciesRaster_intersectList', PACKAGE = 'speciesRaster', input, vec)
}

